group:
  # should match profile/README.md
  #
  # excluded repos:
  # - rfcs: separate issues
  # - rvmob: separate issues
  # - mutiny: separate issues
  # - components: dead repo
  # - awesome-revolt: separate issues
  # - revolt: meta-repo
  # - revolt.py: separate issues
  # - themes: separate issues
  # - translations: separate issues
  repos: |
    revoltchat/revite
    revoltchat/frontend
    revoltchat/android
    revoltchat/ios

    revoltchat/desktop
    revoltchat/android-twa
    revoltchat/fdroid

    revoltchat/backend
    revoltchat/api
    revoltchat/revolt.js
    revoltchat/admin-panel

    revoltchat/vortex
    revoltchat/autumn
    revoltchat/january

    revoltchat/cla
    revoltchat/contributions
    revoltchat/wiki
    revoltchat/genemoji
    revoltchat/legal
    revoltchat/revolt.chat
    revoltchat/self-hosted
  files:
    - source: workflows/triage_issue.yml
      dest: .github/workflows/triage_issue.yml
    - source: workflows/triage_pr.yml
      dest: .github/workflows/triage_pr.yml
